version: "3.8"

services:
  fengsense-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: fengsense-backend
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - TZ=Asia/Bangkok
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - innovation_net

networks:
  innovation_net:
    external: true